{% set name = "apd" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apd-{{ version }}.tar.gz
  sha256: 6ccc1384babf451d460f23e8589c9f8c42ea7957be6d7341910a497b9115e453

build:
  noarch: python
  entry_points:
    - apd-login = apd.command:cmd_login
    - apd-logout = apd.command:cmd_logout
    - apd-cache-info = apd.command:cmd_cache_ap_info
    - apd-list-pfns = apd.command:cmd_list_pfns
    - apd-list-samples = apd.command:cmd_list_samples
    - apd-summary = apd.command:cmd_summary
    - apd-cache-pfns = apd.command:cmd_cache_pfns
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - requests
    - click
    - click-log
    - rich

test:
  imports:
    - apd
  commands:
    - pip check
    - apd-cache-info --help
    - apd-list-pfns --help
    - apd-list-samples --help
  requires:
    - pip

about:
  home: https://pypi.org/project/apd/
  summary: Tool to access the LHCb Analysis production Data
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
